### ISSUE TITLE
ThrdParty\Neslib.Yaml

### ISSUE THREAD

**Issue by limelect** [AliDehbansiahkarbon/OpenAPIClientWizard#1]
ThrdParty\Neslib.Yaml EMPTY !!!!
I had to import nes files including the obj's

**Comment by AliDehbansiahkarbon** [comment]
Added.

**Comment by limelect** [comment]
![Screenshot - 12_06_2024 , 12_30_10](https://github.com/AliDehbansiahkarbon/OpenAPIClientWizard/assets/4199131/c4125f06-6b63-435b-b5d9-841da4156dcb)
You do not need all this junk just add my files that it

**Comment by AliDehbansiahkarbon** [comment]
You're absolutely right, but when I use other's work I prefer to not manipulate or modify anything. In this way I can pull the latest version of 3rd parties directly from their GitHub repository.
