### ISSUE TITLE
Compiled Package misses proper suffix

### ISSUE THREAD

**Issue by UweRaabe** [AliDehbansiahkarbon/OpenAPIClientWizard#2]
Please add a proper suffix to the compiled package. 

While I would suggest _$(Auto)_ for better support of future Delphi versions, users of Delphi versions below 10.4.2 have to tweak that setting a bit to get the desired results.

**Comment by AliDehbansiahkarbon** [comment]
Hi,
Sorry, I'm not sure I got your point correctly.
What is the problem with older IDE versions?

Could you please explain a bit more or create a pull request in this regard?

**Comment by UweRaabe** [comment]
The LIBSUFFIX has previously to be entered literally, like 240 for Delphi 10.1, 250 for Delphi 10.2 and so on.

Since Delphi 10.4 the LIBSUFFIX one can enter $(Auto) as a placeholder for the current Delphi package suffix, like 290 for Delphi 12. See [https://docwiki.embarcadero.com/RADStudio/Athens/en/Description#Library_name](url)

As the repo doesn't provide separate dproj files for different Delphi versions, I suggest to use the $(Auto) approach, which will also work for future versions. Only when compiling for Delphi 10.1 to 10.3 one needs to replace that with the proper value for that version.

Having a Delphi version specific LIBSUFFIX is highly recommended. Otherwise packages compiled with different Delphi versions end up with the same bpl file name.

**Comment by AliDehbansiahkarbon** [comment]
Thank you for the clarification.
Now I understand your point, but I'm curious to know: If you have two different versions of Delphi, let's say Berlin 10.1 and 12, what issues(technically) would arise if both versions use the same package name, considering that their bpl output directories and windows registry keys are different?

**Comment by UweRaabe** [comment]
Well, this might not be of much relevance with design time packages, but some people tend to use the same bpl folder for different Delphi versions (not that I would suggest to do that). Others have just different bpl folders than the _$(BDSCOMMONDIR)\Bpl_ points to. In the latter case, if you are working with runtime packages, you might have that folder added to the global PATH variable. Now the order in there determines which runtime bpl to load - and that can be one compiled with a different Delphi version.

One example is [madExcept](https://madshi.net/madExceptDescription.htm) refusing to add a proper LIBSUFFIX to its bpl files, which are all placed in separate folders different from _$(BDSCOMMONDIR)\Bpl_. While this works inside the IDE, you get some perfect DLL hell when working with runtime packages, because all madExcept packages are named _madExcept.bpl_ when compiled. 

Even if the PATH variable is not used to make Windows find that bpl and you put that bpl into the same folder as the your exe, you are locked to that version and cannot have other exe files in that folder requiring a different madExcept version.

Thus it became good habit to use the LIBSUFFIX to distinguish the same package compiled for different Delphi versions. Here are some links about that topic: 
[Advice for Delphi library authors](https://www.finalbuilder.com/resources/blogs/advice-for-delphi-library-authors)
[Delphi Library Guidelines](https://www.uweraabe.de/Blog/2015/04/20/delphi-library-guidelines/) (yeah, that's me)

**Comment by AliDehbansiahkarbon** [comment]
Perfect explanation.
Thank you.
I will make the necessary changes when I get a chance.

**Comment by AliDehbansiahkarbon** [comment]
Added $(Auto) as LIBSUFFIX.
