### ISSUE TITLE
full demo project

### ISSUE THREAD

**Issue by limelect** [AliDehbansiahkarbon/OpenAPIClientWizard#5]
Ok, I generated a Pascal file what do I do with it?
Can you give a full demo project?

**Comment by AliDehbansiahkarbon** [comment]
Hi,
What is generated is like An SDK, you can implement your design on top of it.
It's not meant to do the whole job and design for you.

**Comment by limelect** [comment]
A demo will help to understand the use of your functions

**Comment by AliDehbansiahkarbon** [comment]
There is a VCL demo app which is enough to get an idea of how to call each generated function.

Please watch the 10-minute video in the dev days webinar.
https://youtu.be/N9XUcMndbtk?t=16389
